### PR TITLE
Feature/merge many paths

### PR DESCRIPTION
**Pull request by 3timeslazy**

### CODE REVIEW

**Comment by mununki** [comment]
Thank you for PR. But, I am really not sure that it needs to parse multiple directories. Generally, putting a project root directory will cover most cases in general.

**Comment by 3timeslazy** [comment]
@mattdamon108 I agree that putting a project root directory will cover most cases. However, merging schema that splitted between 2 paths is a real production case.

**Comment by mununki** [comment]
@3timeslazy Can you explain little more in detail about the case of 2 paths in a real production case?

**Comment by 3timeslazy** [comment]
@mattdamon108 in our company, we have large GraphQL API. API is a union of several services, each with it's own methods. And there is no possibility to put them into single directory.

**Comment by mununki** [comment]
@3timeslazy Alright! Why not to confirm PR for additional feature? ;)

**Comment by mununki** [comment]
@3timeslazy Appreciate your valuable PRs which enriches a feature of this module. Is there any further features in your mind? or I'd like to wrap up and release a new version. Please let me know.

**Comment by 3timeslazy** [comment]
@mattdamon108 this is all for now. Next feature - tests.

**Comment by mununki** [comment]
@3timeslazy Good to know that. I think I need to wrap up and release.

**Pull request merged**
